-   id: nbconvert_rename_precommit
    name: nb_prep (pre-commit; run nbconvert)
    description: 'Converts to .ipynb to .html and adds date prefix and hash placeholder.'
    entry: nbconvert_rename
    language: python
    language_version: python3
    types: [jupyter]
    stages: [commit]
-   id: nbconvert_rename_postcommit
    name: nb_prep (post-commit; replace commithash in .html filenames)
    description: 'Replaces NBCONVERT_RENAME_COMMITHASH_PLACEHOLDER with commit hash in any .html filenames.'
    entry: rename_commithash
    types: [html]    
    language: python
    language_version: python3
    always_run: true
    stages: [post-commit]